#!/bin/bash
OSP_GUID="dcc5"
TOWER_GUID="7acb"
OPENTLC_LOGIN="daniel.zecenaturcios-atos.net"
GITHUB_REPO="https://github.com/dzecena79/ansible_advance_homework"
JQ_REPO_BASE="http://www.opentlc.com/download/ansible_bootcamp"
REGION="us-east-1"
RH_MAIL_ID="daniel.zecenaturcios"
ANSIBLE_ADVANCE_GUID="4347"
